#!/bin/sh
#jkupdate.sh 
# FreeBSD JK Upgrade Script. - CVSUP
# Powered By JackyKit. 2002 - 2003 - 2005
# Version 0.1, 0.2, 0.3, 0.5, 0.9 , 1.0 , 1.1 (28-12-2005)
# Email : jackykit@gmail.com

#新增 freebsd 4.x , 5.x , 6.x 選擇功能

*default host=cvsup.tw.freebsd.org
*default base=/usr
*default prefix=/usr
*default release=cvs tag=RELENG_7
*default delete use-rel-suffix

*default compress

src-all
#ports-all


# These are the individual collections that make up "src-all".  If you
# use these, be sure to comment out "src-all" above.
#src-base
#src-bin
#src-contrib
#src-etc
#src-games
#src-gnu
#src-include
#src-kerberos5
#src-kerberosIV
#src-lib
#src-libexec
#src-release
#src-sbin
#src-share
#src-sys
#src-tools
#src-usrbin
#src-usrsbin
# These are the individual collections that make up FreeBSD's crypto
# collection. They are no longer export-restricted and are a part of
# src-all
#src-crypto
#src-eBones
#src-secure
#src-sys-crypto
